# Generated by Django 4.2.13 on 2024-05-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_options',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='drivers_license_expiry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='drivers_license_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='booking',
            name='car_dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.cardealer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer.car'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
