# Generated by Django 4.2.13 on 2024-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_remove_booking_additional_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rental_days',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rental_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='rent',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
