# Generated by Django 4.2.13 on 2024-06-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='provider',
            new_name='dealer',
        ),
    ]
