# Generated by Django 4.2.13 on 2024-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0002_rename_provider_car_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
